guide(5): Funzioni
DTrombett/guide-bot pull request #7
Opened 2021-08-17 09:04 UTC by DTrombett

### [Funzioni](https://github.com/DTrombett/guide-bot/blob/guide/5/guides/5%20-%20Funzioni.md)

2021-08-21 19:05 UTC, DTrombett commented on guides/5 - Funzioni.md
> +**Nota: questa funzione può essere pericolosa, in quanto il codice potrebbe avere origini sconosciute e verrà eseguito normalmente**
```suggestion
**Nota: questa funzione può essere pericolosa, in quanto il codice potrebbe avere origini sconosciute e verrà eseguito normalmente.**
```

2021-08-21 19:05 UTC, DTrombett commented on guides/5 - Funzioni.md
> +parseFloat("3.14some non-digit characters");
```suggestion
parseFloat("3.14altri caratteri");
```

2021-08-21 19:05 UTC, DTrombett commented on guides/5 - Funzioni.md
> +Decodifica una stringa dal formato URI.
```suggestion
Decodifica una stringa in formato URI.
```

2021-08-21 19:05 UTC, DTrombett commented on guides/5 - Funzioni.md
> +**Restituisce:** `string` - La stringa decodificata dal formato URI.
```suggestion
**Restituisce:** `string` - La stringa decodificata in formato URI.
```

2021-08-21 20:49 UTC, davi-fonto requested changes
correggi, forza

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +Grazie a loro possiamo scrivere delle funzioni in modo più semplici che potranno essere eseguite più velocemente.
ok

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +}; // Se abbiamo 0 o più parametri e vogliamo eseguire più di un azione
```suggestion
}; // Se abbiamo 0 o più parametri e vogliamo eseguire più di un'azione
```

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +}; // Se abbiamo 0 o più parametri e vogliamo eseguire più di un azione
ok

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +	return a + b + chuck;
ok allora correggi anche sotto

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +	return a + b + chuck;
```suggestion
	return a + b + i;
```

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +});
k

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +Ogni funzione deve avere un nome.
k

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> + * Usiamo il jsdoc per specificare il tipo del parametro
k

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +Per farlo usiamo i 3 puntini prima del nome del parametro e nella funzione potremo accedere a quel parametro riferendoci ad un array dei parametri ricevuti.
k

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +Per farlo usiamo i 3 puntini prima del nome del parametro e nella funzione potremo accedere a quel parametro riferendoci ad un array dei parametri ricevuti.
```suggestion
Per farlo usiamo i 3 puntini prima del nome del parametro e nella funzione potremo accedere a quel parametro riferendoci ad un array dei parametri ricevuti.
```
usiamo i 3 puntini???

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +**Nota: è possibile utilizzare solo un rest parameter in una funzione e deve essere collocato obbligatoriamente alla fine.**
```suggestion
**Nota: è possibile utilizzare solo un rest parameter in una funzione e deve essere collocato obbligatoriamente alla fine.**
```
cos'è il rest parameter?

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +const a = (/** b, ... , */ ...c) => {
ok

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +// O con la funzione classica:
ok

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +function a(/** b, ... , */ ...c) {
k

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +**Nota: è possibile utilizzare quanti valori di default vogliamo in una funzione ma devono essere collocati obbligatoriamente alla fine.**
```suggestion
**Nota: è possibile utilizzare quanti valori di default che vogliamo in una funzione ma devono essere collocati obbligatoriamente alla fine.**
```

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +- `d`: Il valore di default che viene assegnato quando il parametro non viene passato o viene passato undefined.
ottimo

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> + * @param {number|string|null} num
kk

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +Dopo aver eseguito le dovute operazioni, la funzione potrà poi restituire un valore con la parola chiave `return`.
okkkk

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +// Questa funzione non usa return ma è un arrow function abbreviata perciò il valore restituito è quello immediatamente dopo la freccia
????
cos'hai cambiato?

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +In generale, si dovrebbe evitare di annidare più funzioni perchè questo porta solo a complicazioni nella lettura e interpretazione del codice, nonchè a un rallentamento nell'esecuzione del codice.
kkkkkkkk

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +Come spiegato nel primo articolo, per dare informazioni al nostro editor riguardo i parametri delle nostre funzioni dobbiamo usare i JSDoc, ossia dei commenti multi-line prima di dichiarare la funzio
ok

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> + * @returns {number[]} I numeri moltiplicati
va bene

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +**Nota: questa funzione può essere pericolosa, in quanto il codice potrebbe avere origini sconosciute e verrà eseguito normalmente**
ok

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +parseFloat("3.14some non-digit characters");
```suggestion
parseFloat("3.14 altri caratteri");
```
che significa?????

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +Decodifica una stringa dal formato URI.
ok

2021-08-21 20:49 UTC, davi-fonto commented on guides/5 - Funzioni.md
> +**Restituisce:** `string` - La stringa decodificata dal formato URI.
va bene

2021-08-21 21:41 UTC, DTrombett commented
Sempre gentile eh

2021-08-21 21:47 UTC, DTrombett commented on guides/5 - Funzioni.md
> +parseFloat("3.14some non-digit characters");
È per mostrare che succede se si aggiungono altri caratteri

2021-08-21 22:04 UTC, DTrombett commented on guides/5 - Funzioni.md
> +// Questa funzione non usa return ma è un arrow function abbreviata perciò il valore restituito è quello immediatamente dopo la freccia
Aggiunto una linea lol

2021-08-21 22:09 UTC, DTrombett commented on guides/5 - Funzioni.md
> +**Nota: è possibile utilizzare quanti valori di default vogliamo in una funzione ma devono essere collocati obbligatoriamente alla fine.**
Così suona male :/
O "quanti valori di default vogliamo" o "tutti i valori di default che vogliamo"

2021-08-21 22:13 UTC, DTrombett commented on guides/5 - Funzioni.md
> +**Nota: è possibile utilizzare solo un rest parameter in una funzione e deve essere collocato obbligatoriamente alla fine.**
L'ho appena spiegato :/
È quando vuoi ricevere più parametri insieme...

2021-08-21 22:16 UTC, DTrombett commented on guides/5 - Funzioni.md
> +Per farlo usiamo i 3 puntini prima del nome del parametro e nella funzione potremo accedere a quel parametro riferendoci ad un array dei parametri ricevuti.
Exactly. Usiamo i 3 puntini prima del nome del parametro. Forte, eh? XD

2021-08-21 22:22 UTC, davi-fonto submitted a review, later dismissed

2021-08-22 08:39 UTC, DTrombett commented on guides/5 - Funzioni.md
> +- `b, ...c`: I parametri della funzione.
```suggestion
- `b, ...c`: I parametri della funzione.

```

2021-08-22 08:43 UTC, merged